#blog index listing articles and categories
stvn_blog_homepage:
    path:     /blog/index/{categoryId}
    defaults: { _controller: StvnBlogBundle:Default:index, categoryId:0 }

#display blog article
stvn_blog_detail:
    path:      /blog/detail/{id}
    defaults: { _controller: StvnBlogBundle:Default:detail }

#add new category
stvn_blog_addcategory:
    path:     /blog/category
    defaults: { _controller: StvnBlogBundle:Default:addCategory }

#modify specified category
stvn_blog_editcategory:
    path:     /blog/category/{id}
    defaults: { _controller: StvnBlogBundle:Default:editCategory }

#add new article
stvn_blog_addarticle:
    path:     /blog/article
    defaults: { _controller: StvnBlogBundle:Default:addArticle }

#modify specified article
stvn_blog_editarticle:
    path:     /blog/article/{id}
    defaults: { _controller: StvnBlogBundle:Default:editArticle }
