parameters:
#    stvn_blog.example.class: Stvn\BlogBundle\Example

services:
#    stvn_blog.example:
#        class: %stvn_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
