<?php

namespace Stvn\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Stvn\BlogBundle\Entity\Article;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function addAritlce(Article $article){
        
    }
}
